DemonHulk/Transparencia-Frontend

- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/components/articulo33/articulo33.component.css
- src/app/components/articulo33/articulo33.component.html
- src/app/components/articulo33/articulo33.component.spec.ts
- src/app/components/articulo33/articulo33.component.ts
- src/app/components/articulo33/contenido-punto/contenido-punto.component.html
- src/app/components/articulo33/contenido-punto/contenido-punto.component.spec.ts
- src/app/components/articulo33/contenido-punto/contenido-punto.component.ts
- src/app/partials/titulo/titulo.component.css
- src/app/partials/titulo/titulo.component.html
- src/app/partials/titulo/titulo.component.spec.ts
- src/app/partials/titulo/titulo.component.ts
- src/styles.css
Template del Artículo 33, Revisar Responsiva, El diseño, que no haya errores.
> Frontend articulo33

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/new-pdf/new-pdf.component.html
- src/app/components/forms/new-pdf/new-pdf.component.spec.ts
- src/app/components/forms/new-pdf/new-pdf.component.ts
- src/app/components/login/login.component.html
- src/app/partials/footer/footer.component.html
- src/app/partials/titulo/titulo.component.html
El template para el formulario para dar de alta un nuevo archivo PDF en el sistema
> Frontend formulario archivo

- src/app/partials/footer/footer.component.html
- src/app/partials/header/header.component.css
- src/app/partials/header/header.component.html
- src/styles.css
Un diseño provisional simplemente para el funcionamiento y guía de sistema en lo que se proporciona el original por parte del Equipo Principal
> Diseño del Navbar provisional

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/new-punto/new-punto.component.html
- src/app/components/forms/new-punto/new-punto.component.spec.ts
- src/app/components/forms/new-punto/new-punto.component.ts
- src/app/partials/header/header.component.html
El  template para el formulario para registrar un nuevo punto
> Formulario para registrar un nuevo punto

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/articulo33/articulo33.component.ts
- src/app/components/forms/edit-area/edit-area.component.html
- src/app/components/forms/edit-area/edit-area.component.spec.ts
- src/app/components/forms/edit-area/edit-area.component.ts
- src/app/components/forms/new-area/new-area.component.html
- src/app/components/forms/new-area/new-area.component.spec.ts
- src/app/components/forms/new-area/new-area.component.ts
- src/app/components/forms/new-pdf/new-pdf.component.ts
- src/app/components/login/login.component.ts
- src/app/components/tables/list-areas/details-area/details-area.component.html
- src/app/components/tables/list-areas/details-area/details-area.component.spec.ts
- src/app/components/tables/list-areas/details-area/details-area.component.ts
- src/app/components/tables/list-areas/list-areas.component.html
- src/app/components/tables/list-areas/list-areas.component.spec.ts
- src/app/components/tables/list-areas/list-areas.component.ts
- src/app/partials/header/header.component.html
- src/app/partials/page-not-found/page-not-found.component.html
- src/app/partials/titulo/titulo.component.html
- src/app/partials/titulo/titulo.component.ts
- src/app/services/shared-values.service.spec.ts
- src/app/services/shared-values.service.ts
Revisar todo lo relacion a Areas, funciona el menu donde indica Administrar area, Agregar Area, Modificar Area, Detalle area, (TEMPLATES)
> Forntend administrar trimestres

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/edit-pdf/edit-pdf.component.html
- src/app/components/forms/edit-pdf/edit-pdf.component.spec.ts
- src/app/components/forms/edit-pdf/edit-pdf.component.ts
- src/app/components/forms/edit-punto/edit-punto.component.html
- src/app/components/forms/edit-punto/edit-punto.component.spec.ts
- src/app/components/forms/edit-punto/edit-punto.component.ts
- src/app/components/forms/edit-subtema/edit-subtema.component.html
- src/app/components/forms/edit-subtema/edit-subtema.component.spec.ts
- src/app/components/forms/edit-subtema/edit-subtema.component.ts
- src/app/components/forms/edit-tema/edit-tema.component.html
- src/app/components/forms/edit-tema/edit-tema.component.spec.ts
- src/app/components/forms/edit-tema/edit-tema.component.ts
- src/app/components/forms/new-subtema/new-subtema.component.html
- src/app/components/forms/new-subtema/new-subtema.component.spec.ts
- src/app/components/forms/new-subtema/new-subtema.component.ts
- src/app/components/forms/new-tema/new-tema.component.html
- src/app/components/forms/new-tema/new-tema.component.spec.ts
- src/app/components/forms/new-tema/new-tema.component.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.spec.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.ts
- src/app/components/tables/list-puntos/list-puntos.component.html
- src/app/components/tables/list-puntos/list-puntos.component.spec.ts
- src/app/components/tables/list-puntos/list-puntos.component.ts
- src/app/partials/header/header.component.html
- src/styles.css
Todas las vistas para administrar puntos desde formularios hasta los funcionamientos
> Frontend template administrar punto

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/articulo33/contenido-punto/contenido-punto.component.html
- src/app/components/forms/edit-pdf/edit-pdf.component.html
- src/app/components/forms/edit-trimestre/edit-trimestre.component.html
- src/app/components/forms/edit-usuario/edit-usuario.component.html
- src/app/components/forms/edit-usuario/edit-usuario.component.spec.ts
- src/app/components/forms/edit-usuario/edit-usuario.component.ts
- src/app/components/forms/new-pdf/new-pdf.component.html
- src/app/components/forms/new-trimestre/new-trimestre.component.html
- src/app/components/forms/new-usuario/new-usuario.component.html
- src/app/components/forms/new-usuario/new-usuario.component.spec.ts
- src/app/components/forms/new-usuario/new-usuario.component.ts
- src/app/components/mi-perfil/mi-perfil.component.html
- src/app/components/tables/list-areas/list-areas.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/components/tables/list-puntos/list-puntos.component.html
- src/app/components/tables/list-trimestres/list-trimestres.component.html
- src/app/components/tables/list-usuarios/details-usuario/details-usuario.component.html
- src/app/components/tables/list-usuarios/details-usuario/details-usuario.component.spec.ts
- src/app/components/tables/list-usuarios/details-usuario/details-usuario.component.ts
- src/app/components/tables/list-usuarios/list-usuarios.component.html
- src/app/components/tables/list-usuarios/list-usuarios.component.spec.ts
- src/app/components/tables/list-usuarios/list-usuarios.component.ts
- src/app/partials/header/header.component.html
- src/app/partials/page-not-found/page-not-found.component.html
- tailwind.config.js
Revisar todo lo relacionado Administrar usuarios
> Frontend administrar usuarios

- src/app/components/forms/edit-area/edit-area.component.html
- src/app/components/forms/edit-pdf/edit-pdf.component.html
- src/app/components/forms/edit-perfil/edit-perfil.component.html
- src/app/components/forms/edit-punto/edit-punto.component.html
- src/app/components/forms/edit-subtema/edit-subtema.component.html
- src/app/components/forms/edit-tema/edit-tema.component.html
- src/app/components/forms/edit-trimestre/edit-trimestre.component.html
- src/app/components/forms/edit-usuario/edit-usuario.component.html
- src/app/components/forms/new-area/new-area.component.html
- src/app/components/forms/new-pdf/new-pdf.component.html
- src/app/components/forms/new-punto/new-punto.component.html
- src/app/components/forms/new-subtema/new-subtema.component.html
- src/app/components/forms/new-tema/new-tema.component.html
- src/app/components/forms/new-trimestre/new-trimestre.component.html
- src/app/components/forms/new-usuario/new-usuario.component.html
- tailwind.config.js
Se cambio el de diseño de los elementos de los formularios
> Frontend mejora inputs forms

- .gitignore
- node_modules/.package-lock.json
> Archivo gitignore

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/new-word/new-word.component.html
- src/app/components/forms/new-word/new-word.component.spec.ts
- src/app/components/forms/new-word/new-word.component.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/styles.css
Revisar que funcione el preview del contenido estatico
> Frontend formulario estatico

- src/app/app.module.ts
- src/app/services/api-config.ts
- src/app/services/crud/areacrud.service.spec.ts
- src/app/services/crud/areacrud.service.ts
Se agrego la estructura base de un servicio, la api en un archivo global y los imports necesarios para los formularios
> Estructura-Base-Servicios

- src/app/components/tables/list-areas/details-area/details-area.component.html
- src/app/components/tables/list-areas/details-area/details-area.component.ts
- src/app/components/tables/list-areas/list-areas.component.html
- src/app/components/tables/list-areas/list-areas.component.ts
- src/styles.css
Un ejemplo de como aplicar skeleton para los próximos funcionamientos en desarrollo, confirmar el correcto funcionamiento del skeleton, probar bajar la velocidad del internet desde el apartado de red en F12 para ver el funcionamiento
> Skeleton Areas

- src/app/components/forms/edit-area/edit-area.component.html
- src/app/components/forms/edit-area/edit-area.component.ts
- src/app/components/forms/new-area/new-area.component.html
- src/app/components/forms/new-area/new-area.component.ts
- src/app/services/api-config.ts
- tailwind.config.js
El funcionamiento de validators para las validaciones en tiempo real de los formularios, revisar el correcto funcionamiento en el alta de areas asi mismo en el editar
> Validators Area

- src/app/components/forms/new-area/new-area.component.html
- src/app/components/tables/list-areas/list-areas.component.html
se elimino la acción de editar en el listado de papelera y se modifico la función de editar área y modificar usuario por lo que
se requiere revisar el correcto funcionamiento de editar Área y editar Usuario
> Eliminación de Acciones en área

- src/app/components/forms/edit-area/edit-area.component.ts
- src/app/components/forms/edit-usuario/edit-usuario.component.ts
- src/app/components/forms/new-area/new-area.component.ts
- src/app/components/forms/new-usuario/new-usuario.component.ts
- src/app/components/login/login.component.ts
- src/app/components/tables/list-areas/details-area/details-area.component.html
- src/app/components/tables/list-areas/details-area/details-area.component.ts
- src/app/components/tables/list-areas/list-areas.component.ts
- src/app/components/tables/list-usuarios/details-usuario/details-usuario.component.ts
- src/app/components/tables/list-usuarios/list-usuarios.component.ts
- src/app/services/crud/areacrud.service.ts
- src/app/services/crud/puntosareascrud.service.ts
- src/app/services/crud/usuariocrud.service.ts
- src/app/services/cryptoService/crypto-service.service.ts
- src/app/services/login/login.service.ts
Revisar que las respuestas que envía el backend estén encriptadas, así como el correcto funcionamiento de las funcionalidades de área y usuarios
> Backend encriptar desencriptar datos usuario

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.html
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.spec.ts
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.ts
- src/app/components/forms/new-ejercicio/new-ejercicio.component.html
- src/app/components/forms/new-ejercicio/new-ejercicio.component.spec.ts
- src/app/components/forms/new-ejercicio/new-ejercicio.component.ts
- src/app/components/tables/list-ejercicio/list-ejercicio.component.html
- src/app/components/tables/list-ejercicio/list-ejercicio.component.spec.ts
- src/app/components/tables/list-ejercicio/list-ejercicio.component.ts
- src/app/partials/header/header.component.html
Diseño de tabla y formularios para mostrar y administrar los ejercicios
> Diseño de templates para ejercicios

- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.html
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.ts
- src/app/components/forms/new-ejercicio/new-ejercicio.component.html
- src/app/components/forms/new-ejercicio/new-ejercicio.component.ts
- src/app/components/tables/list-areas/list-areas.component.html
- src/app/components/tables/list-ejercicio/list-ejercicio.component.html
- src/app/components/tables/list-ejercicio/list-ejercicio.component.ts
- src/app/components/tables/list-usuarios/list-usuarios.component.html
- src/app/services/api-config.ts
- src/app/services/crud/ejerciciocrud.service.spec.ts
- src/app/services/crud/ejerciciocrud.service.ts
Funcionamiento del CRUD de Ejercicio.
> CRUD de Ejercicio

- src/app/components/forms/edit-trimestre/edit-trimestre.component.html
- src/app/components/forms/edit-trimestre/edit-trimestre.component.ts
- src/app/components/forms/new-trimestre/new-trimestre.component.html
- src/app/components/forms/new-trimestre/new-trimestre.component.ts
- src/app/components/tables/list-trimestres/list-trimestres.component.html
- src/app/components/tables/list-trimestres/list-trimestres.component.ts
- src/app/services/api-config.ts
- src/app/services/crud/trimestrecrud.service.spec.ts
- src/app/services/crud/trimestrecrud.service.ts
Se implementaron los CRUD de trimestre, por lo que se requiere revisar su correcto funcionamiento, desde la inserción hasta la eliminación.
> Backend crud trimestre

- src/app/components/forms/edit-area/edit-area.component.ts
- src/app/components/forms/edit-punto/edit-punto.component.html
- src/app/components/forms/edit-punto/edit-punto.component.ts
- src/app/components/forms/edit-trimestre/edit-trimestre.component.html
- src/app/components/forms/edit-trimestre/edit-trimestre.component.ts
- src/app/components/forms/new-punto/new-punto.component.html
- src/app/components/forms/new-punto/new-punto.component.ts
- src/app/components/forms/new-trimestre/new-trimestre.component.html
- src/app/components/forms/new-trimestre/new-trimestre.component.ts
- src/app/components/tables/list-puntos/list-puntos.component.html
- src/app/components/tables/list-puntos/list-puntos.component.ts
- src/app/services/api-config.ts
- src/app/services/crud/areacrud.service.ts
- src/app/services/crud/puntocrud.service.spec.ts
- src/app/services/crud/puntocrud.service.ts
- src/app/services/crud/puntosareascrud.service.ts
Revisar el correcto funcionamiento del modulo trimestre, donde se requiere revisar el funcionamiento desde diferentes usuarios con diferentes áreas.
> Backend crud punto

- src/app/app.module.ts
- src/app/components/forms/edit-area/edit-area.component.ts
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.ts
- src/app/components/forms/edit-perfil/edit-perfil.component.ts
- src/app/components/forms/edit-punto/edit-punto.component.ts
- src/app/components/forms/edit-trimestre/edit-trimestre.component.ts
- src/app/components/forms/edit-usuario/edit-usuario.component.ts
- src/app/components/forms/new-punto/new-punto.component.ts
- src/app/components/forms/new-trimestre/new-trimestre.component.ts
- src/app/components/forms/new-usuario/new-usuario.component.ts
- src/app/components/mi-perfil/mi-perfil.component.html
- src/app/components/mi-perfil/mi-perfil.component.ts
- src/app/components/tables/list-areas/details-area/details-area.component.ts
- src/app/components/tables/list-areas/list-areas.component.ts
- src/app/components/tables/list-ejercicio/list-ejercicio.component.ts
- src/app/components/tables/list-puntos/list-puntos.component.ts
- src/app/components/tables/list-trimestres/list-trimestres.component.ts
- src/app/components/tables/list-usuarios/details-usuario/details-usuario.component.ts
- src/app/components/tables/list-usuarios/list-usuarios.component.ts
- src/app/partials/error-loading/error-loading.component.html
- src/app/partials/error-loading/error-loading.component.spec.ts
- src/app/partials/error-loading/error-loading.component.ts
- src/app/partials/page-not-found/page-not-found.component.html
- src/app/services/api-config.ts
- src/app/services/shared-values.service.ts
- src/styles.css
- Se implementó el manejo de errores para la pantalla de carga en varias funciones del servicio.
- Se añadió la función `updateErrorLoading` en los bloques de manejo de errores para mostrar mensajes específicos al usuario cuando falla la carga de datos.
- Se aseguró que la pantalla de carga se desactive correctamente incluso en caso de error.
Cambios realizados:
- Actualización de funciones para incluir `updateErrorLoading` y mensajes de error personalizados.
- Mejoras en la gestión de errores para proporcionar una experiencia de usuario más informativa y amigable.
Detalles adicionales:
- Se emplearon métodos específicos del servicio `sharedService` para actualizar el estado de carga y manejar errores visuales.
> Pantalla de Error Loading

- src/app/components/forms/edit-tema/edit-tema.component.html
- src/app/components/forms/edit-tema/edit-tema.component.ts
- src/app/components/forms/new-tema/new-tema.component.html
- src/app/components/forms/new-tema/new-tema.component.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.css
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.ts
- src/app/services/api-config.ts
- src/app/services/crud/tituloscrud.service.spec.ts
- src/app/services/crud/tituloscrud.service.ts
Se agrego en detalles punto, el alta de un nuevo tema, desactivar, activar, y editarlo. 
revisar que funcione bien el loader de UTC.
y que las alertas arrojen bien la accion que se esta ejecutando
> Backend-CRUD-Titulos

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/forms/edit-pdf/edit-pdf.component.html
- src/app/components/forms/edit-pdf/edit-pdf.component.ts
- src/app/components/forms/edit-perfil/edit-perfil.component.ts
- src/app/components/forms/edit-word/edit-word.component.html
- src/app/components/forms/edit-word/edit-word.component.spec.ts
- src/app/components/forms/edit-word/edit-word.component.ts
- src/app/components/forms/new-pdf/new-pdf.component.html
- src/app/components/forms/new-pdf/new-pdf.component.ts
- src/app/components/forms/new-word/new-word.component.html
- src/app/components/forms/new-word/new-word.component.ts
- src/app/components/mi-perfil/mi-perfil.component.html
- src/app/components/mi-perfil/mi-perfil.component.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.css
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.ts
- src/app/partials/header/header.component.html
- src/app/services/api-config.ts
- src/app/services/crud/contenidocrud.service.spec.ts
- src/app/services/crud/contenidocrud.service.ts
Se requiere revisar los la funcionalidad del alta de contenido estático y dinámico, inserción, edición, eliminar y activar, además de revisar la funcionalidad del apartado mi perfil.
se agrego la funcionalidad de visualización del documento haciendo clic en el nombre del archivo.
> Backend crud contenido

- src/app/app-routing.module.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/components/forms/edit-pdf/edit-pdf.component.ts
- src/app/components/forms/edit-subtema/edit-subtema.component.ts
- src/app/components/forms/new-pdf/new-pdf.component.ts
- src/app/components/forms/new-punto/new-punto.component.ts
- src/app/components/forms/new-subtema/new-subtema.component.ts
- src/app/components/forms/new-tema/new-tema.component.ts
- src/app/components/login/login.component.ts
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.html
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.spec.ts
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.ts
- src/app/services/shared-values.service.ts
Aprobar el diseño de subtema, tambien probar la nueva funcionalidad que al cargar o cambiar de pestaña siempre debe ponerse la pantalla hasta arriba, tambien se elimino el antiguo **Load Script**
> Nuevo template de  Administrar subtemas

- src/app/components/articulo33/articulo33.component.html
- src/app/components/articulo33/contenido-punto/contenido-item/contenido-item.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/styles.css
Las clases adaptadas al diseño para el correcto funcionamiento
> Clases y CSS

- src/app/components/login/login.component.html
- src/app/partials/header/header.component.html
Se arreglo el bug de cuando aparecian las alertas en el login el formulario crecia y se movia todo lo que lo contenia junto a la imagen de la izquierda. Se movio el la palabra TRANSPARENCIA mas hacia la derecha.
> rediseño del iniciar sesión y header

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/tables/list-puntos/administrar-orden/administrar-orden.component.css
- src/app/components/tables/list-puntos/administrar-orden/administrar-orden.component.html
- src/app/components/tables/list-puntos/administrar-orden/administrar-orden.component.spec.ts
- src/app/components/tables/list-puntos/administrar-orden/administrar-orden.component.ts
- src/app/components/tables/list-puntos/list-puntos.component.html
- src/app/components/tables/list-puntos/list-puntos.component.ts
- src/app/services/api-config.ts
- src/app/services/crud/puntocrud.service.ts
Revisar el correcto funcionamiento del Administrar odern
> Backend orden punto

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/articulo33/articulo33.component.html
- src/app/components/forms/new-punto/new-punto.component.ts
- src/app/components/forms/password-recovery/password-recovery.component.html
- src/app/components/forms/password-recovery/password-recovery.component.spec.ts
- src/app/components/forms/password-recovery/password-recovery.component.ts
- src/app/components/login/login.component.html
- src/app/services/api-config.ts
- src/app/services/login/recovery-password.service.spec.ts
- src/app/services/login/recovery-password.service.ts
Se implementó la funcionalidad de recuperación de contraseña mediante un correo de Gmail, donde se enviará la nueva contraseña. 
Se requiere revisar el correcto funcionamiento de la recuperación de la contraseña haciendo uso de un correo real registrado en el sistema.
> Backend crud recuperar contrasenia

- src/app/app.module.ts
- src/app/components/articulo33/contenido-punto/contenido-item/contenido-item.component.ts
- src/app/components/forms/new-pdf/new-pdf.component.ts
- src/app/components/tables/list-puntos/details-punto/subtemas/contenido-subtema/contenido-subtema.component.html
- src/app/components/tables/list-puntos/details-punto/subtemas/contenido-subtema/contenido-subtema.component.ts
- src/app/components/tables/list-puntos/details-punto/subtemas/recursive-nav-item/recursive-nav-item.component.html
- src/app/components/tables/list-puntos/details-punto/subtemas/recursive-nav-item/recursive-nav-item.component.spec.ts
- src/app/components/tables/list-puntos/details-punto/subtemas/recursive-nav-item/recursive-nav-item.component.ts
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.html
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.ts
- src/app/services/crud/tituloscrud.service.ts
Se cambio la forma en la que se muestran los subtemas
> Reestructuracion del diseño

- src/app/components/articulo33/articulo33.component.css
- src/app/components/articulo33/articulo33.component.html
- src/app/components/skeleton/loading-spinner/loading-spinner.component.css
- src/app/components/tables/list-puntos/details-punto/subtemas/subtemas.component.html
- src/styles.css
Se agregaron clases y funciones para la responsiva
> Se agregan clases para mejorar la responsiva

- src/app/components/articulo33/contenido-punto/contenido-item/contenido-item.component.html
- src/app/components/forms/edit-area/edit-area.component.html
- src/app/components/forms/edit-ejercicio/edit-ejercicio.component.html
- src/app/components/forms/edit-pdf/edit-pdf.component.html
- src/app/components/forms/edit-punto/edit-punto.component.html
- src/app/components/forms/edit-subtema/edit-subtema.component.html
- src/app/components/forms/edit-tema/edit-tema.component.html
- src/app/components/forms/edit-trimestre/edit-trimestre.component.html
- src/app/components/forms/edit-usuario/edit-usuario.component.html
- src/app/components/forms/new-area/new-area.component.html
- src/app/components/forms/new-ejercicio/new-ejercicio.component.html
- src/app/components/forms/new-pdf/new-pdf.component.html
- src/app/components/forms/new-punto/new-punto.component.html
- src/app/components/forms/new-subtema/new-subtema.component.html
- src/app/components/forms/new-tema/new-tema.component.html
- src/app/components/forms/new-trimestre/new-trimestre.component.html
- src/app/components/forms/new-usuario/new-usuario.component.html
- src/app/components/tables/list-puntos/details-punto/details-punto.component.html
- src/app/partials/header/header.component.html
Responsivas del menu.
Cambio de mensajes en los (?) de los formularios
> Menu y mensajes
